#!/bin/bash

# Formatting drives and setting up swap
mkfs.fat -F32 /dev/sda1
mkswap /dev/sda2
swapon /dev/sda2
mkfs.ext4 /dev/sda3
mkfs.ext4 /dev/sda4

# Mounting root partition
mount /dev/sda3 /mnt

# Creating home folder in /mnt
mkdir /mnt/home

# Mounting home partition
mount /dev/sda4 /mnt/home

# Configuring /etc/pacman.d/mirrorlist with reflector
#reflector -f 12 -l 10 -n 12 --save /etc/pacman.d/mirrorlist

# Updating mirrors and downloading base for install
pacman -Syy
pacstrap /mnt base base-devel linux linux-firmware nano

# Generating /etc/fstab on new system
genfstab -U /mnt >> /mnt/etc/fstab

# Moving configuration files to new system
mv part2 /mnt
mv part3 /mnt

# Chroot into new system
arch-chroot /mnt
