#!/bin/bash

echo File is configured to format drives please change in config
read -p Ctrl + c to abort

# Formatting drives and setting up swap
mkfs.fat -F32 /dev/sda1
mkswap /dev/sda2
swapon /dev/sda2
mkfs.ext4 /dev/sda3
mkfs.ext4 /dev/sda4

# Mounting root partition
mount /dev/sda3 /mnt

# Creating home folder in /mnt
mkdir /mnt/home

# Mounting home partition
mount /dev/sda4 /mnt/home

# Setting up pacman.conf
cp pacman.conf /etc/pacman.conf

# Configuring /etc/pacman.d/mirrorlist with reflector
reflector -f 12 -l 10 -n 12 --save /etc/pacman.d/mirrorlist

# Updating mirrors and downloading base for install
pacman -Syy
pacstrap /mnt base linux linux-firmware nano base-devel

# Generating /etc/fstab on new system
genfstab -U /mnt >> /mnt/etc/fstab

# Copying pacman configuration to new system
cp mirrorlist /mnt/etc/pacman.d/mirrorlist
cp /etc/pacman.conf /mnt/etc/pacman.conf

# Moving configuration files to new system
mv part2 /mnt
mv moddas /mnt

# Instructions to continue
echo --------------------------------------
echo To continue configuration type ./part2
echo --------------------------------------

# Chroot into new system
arch-chroot /mnt
