#!/bin/bash

# Setting up timezone
ln -sf /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
hwclock --systohc

# Setting up locale
echo sv_SE.UTF-8 UTF-8 >> /etc/locale.gen
echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
locale-gen
echo LANG=sv_SE.UTF-8 >> /etc/locale.conf
echo KEYMAP=sv-latin1 >> /etc/vconsole.conf

# Setting up /etc/hostname
echo arch-desktop >> /etc/hostname
echo 127.0.0.1	localhost >> /etc/hosts
echo ::1		    localhost >> /etc/hosts
echo 127.0.1.1  arch-desktop >> /etc/hosts
echo ::1        localhost ip6-localhost ip6-loopback
echo ff02::1    ip6-allnodes
echo ff02::2    ip6-allrouters
echo make sure spacing is correct >> /etc/hosts
nano /etc/hosts

# Starting installation 
pacman -Syy
pacman-key --populate archlinux
passwd

# Install packages
# Chose desktop environment by adding kde, gnome, cinnamon, mate behind <
pacman -S - < 

# Preparing boot partition and installing systemd-boot
mkdir /boot
mount /dev/sda1 /boot
bootctl --path=/boot install
echo default arch-* >> /boot/loader/loader.conf
echo clear default line with numbers >> /boot/loader/loader.conf
nano /boot/loader/loader.conf
touch /boot/loader/entries/arch.conf
echo title  Arch Linux >> /boot/loader/entries/arch.conf
echo linux  /vmlinuz-linux >> /boot/loader/entries/arch.conf
echo initrd /initramfs-linux.img >> /boot/loader/entries/arch.conf
echo options  root=/dev/sda3 rw >> /boot/loader/entries/arch.conf
echo make sure spacing is correct >> /boot/loader/entries/arch.conf
nano /boot/loader/entries/arch.conf

# Enabling Services and adding accounts
systemctl enable sddm.service
systemctl enable NetworkManager
useradd -m modda
passwd modda
xdg-user-dirs-update
EDITOR=nano visudo
mv /part3 /home/modda/part3
cd /home/modda
su modda
echo "-----------------"
echo "All set and done!"
echo "-----------------"
