#!/bin/bash
# Formatting drives and setting up swap
mkfs.fat -F32 /dev/sda1
mkswap /dev/sda2
swapon /dev/sda2
mkfs.ext4 /dev/sda3

# Mounting root partition
mount /dev/sda3 /mnt

# Installing base system
pacstrap /mnt base base-devel linux linux-firmware nano

# Generating /etc/fstab on new system
genfstab -U /mnt >> /mnt/etc/fstab

# Moving configuration files to new system
mv install /mnt
mv user /mnt

# Chroot into new system
arch-chroot /mnt
