#!/bin/bash
# Formatting drives and setting up swap
mkfs.fat -F32 /dev/nvme0n1p1
mkswap /dev/nvme0n1p2
swapon /dev/nvme0n1p2
mkfs.ext4 /dev/nvme0n1p3
#mkfs.ext4 /dev/nvme1n1p1

# Mounting root partition
mount /dev/nvme0n1p3 /mnt

# Installing base system
pacstrap /mnt base base-devel linux linux-firmware nano

# Generating /etc/fstab on new system
genfstab -U /mnt >> /mnt/etc/fstab

# Moving configuration files to new system
mv install /mnt
mv user /mnt

# Chroot into new system
arch-chroot /mnt
