#!/bin/bash
# Installing git and yay
cd /opt
sudo git clone https://aur.archlinux.org/yay-git.git
sudo chown -R modda:modda ./yay-git
cd yay-git
makepkg -si

# Updating yay
yay -Syy

# Installing spotify
curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | gpg --import -
yay -S spotify

# Installing steam-fonts
yay -S steam-fonts 

# Installing and enabling Optimus Manager and gdm-prime fix
yay -S optimus-manager-qt-git gdm-prime
sudo systemctl enable optimus-manager.service

# Changing shell to fish
chsh -s /usr/bin/fish
sudo chsh -s /usr/bin/fish
